services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genai-ms
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "80:80"